### ISSUE TITLE
write problem

### ISSUE THREAD

**Issue by diverdude** [kinverarity1/las-reader#32]
I am reading in this file: http://www.kgs.ku.edu/software/PfEFFER-java/HELP/New_Session/12345b.las
which seems to work fine. then
l = las_reader.read("12345a.las")

Then i try to write it using:
l.write('foo.las',2)

but this gives me an error:
<ipython-input-4-d988d13adafd> in <module>()
----> 1 l.write('foo.las')

/home/bdi/virtualenvs/p27/local/lib/python2.7/site-packages/las_reader/las.pyc in write(self, file, version)
    251                 l_value = len(str(vm.value))
    252         for vm in list(self.version.values()):
--> 253             vm_d = vm.todict()
    254             vm_d['mnemonic'] = vm_d['mnemonic'].rjust(l_mnem)
    255             vm_d['value'] = str(vm_d['value']).rjust(l_value)

AttributeError: 'Metadata' object has no attribute 'todict'

Is there an example on how i should write a file?
Can this library actually write las 2.0 files?

**Comment by kinverarity1** [comment]
Strange error, I'm finding it too. Looking into it.

**Comment by kinverarity1** [comment]
1. Try updating to the latest version (0.4.1) either via pip or the releases page here on Github. The code shown there on lines 251-255 is old code where it was unable to write las 2.0 files properly.

2. The write method needs an open file-like object rather than a filename -- I've added a docstring to make this clear. So use for example:

```python
l = las_reader.read("12345b.las")
with open("12345b_version2test.las", mode="w") as f:
    l.write(f, 2)
```

That is working for me. Let me know if you still have a problem.

**Comment by kinverarity1** [comment]
...and thanks for the suggestion, I will put an example in the readme.
