### ISSUE TITLE
python 3 version

### ISSUE THREAD

**Issue by diverdude** [kinverarity1/las-reader#34]
First of all, thanks for just really finally building a las-lib that is easy to install and easy to use. 
Definitly the best las library i have seen. 
I wanted to try and contribute by converting to python 3 (i am a p3 user) but when i cloned your repo i saw you already have a p2->p3 branch. so i checked that out, and it seems its just an older version.
Would there be an easy way to get the p3 version of you lib updated so its working with your v. 0.5 demos?

**Comment by kinverarity1** [comment]
No problem, thanks for trying it out and contributing!

Yes the py3 branch is old -- the intention at least for now is that master should run without changes on both Python 2 and 3, but I haven't yet got a working Python 3 system to test regularly with. Otherwise yes help would be very welcome to investigate what the incompatabilities are, and then we can fix it and keep the py3 branch up to date. Try master on python 3 -- I'm curious to see what errors may pop up.

(IIRC the only thing that differs, at least as of a week or so ago, is the location of ``StringIO`` in the standard library, and I put in a convoluted set of ``try ... except`` statements at the top to cope with both 2 and 3).

**Comment by diverdude** [comment]
i will try and update to P3 by comparing your P2 version...basically there are some minor differences. I will give you a pull request after

**Comment by diverdude** [comment]
Hi, i tried to push to a new branch with an update, but i get permission denied error: 
remote: Permission to kinverarity1/las-reader.git denied to diverdude.
fatal: unable to access 'https://github.com/kinverarity1/las-reader.git/': The requested URL returned error: 403

There was just some import statements i had to change.
I will update and make pull request if you give me access

**Comment by kinverarity1** [comment]
Fork las_reader first and push the new branch to your fork. Then open a PR from there.

Thanks for making the changes!
